// shadowFilmStudy.ts — Film Study vision pipeline: sampling policy, frame
// extraction, and the vision model call.
//
// This is prerequisite scaffolding, not the feature. #103 orders measured
// facts (vision latency and token spend per frame batch, in-container
// extraction time) BEFORE the executor is written, so this module currently
// powers only the admin measurement diagnostic
// (/api/pilot/shadow/film-study/diagnostic). The film_study job type stays
// SHADOW_JOB_TYPE_UNAVAILABLE in shadowJobProcessor.ts until those
// measurements exist and the safety design on #103 is approved.
//
// OFF by default, per the deploy rules: vision calls require
// AZURE_AI_VISION_DEPLOYMENT_NAME alongside the AZURE_AI_ENDPOINT /
// AZURE_AI_KEY the chat models already use.

import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

// The sampling policy IS the cost model (#103 prerequisite 1): per-video
// vision cost is frames × image-tokens, so these are stated constants, not
// tuning knobs. One frame every 2 seconds, hard cap 90 frames — a 3-minute
// clip at full sampling. Changing either number is an owner cost decision
// made on #103, and the executor must import these rather than restate them.
export const FILM_STUDY_FRAME_INTERVAL_SECONDS = 2;
export const FILM_STUDY_MAX_FRAMES_PER_JOB = 90;

const FFMPEG_TIMEOUT_MS = 60_000;
const VISION_TIMEOUT_MS = 120_000;
const VISION_MAX_COMPLETION_TOKENS = 4_096;
const MAX_FRAME_BYTES = 5 * 1024 * 1024;

export function getVisionDeploymentName(
  env: Record<string, string | undefined> = process.env,
): string {
  return env.AZURE_AI_VISION_DEPLOYMENT_NAME?.trim() ?? '';
}

export function isFilmStudyVisionConfigured(
  env: Record<string, string | undefined> = process.env,
): boolean {
  return Boolean(
    getVisionDeploymentName(env)
    && env.AZURE_AI_ENDPOINT?.trim()
    && env.AZURE_AI_KEY?.trim(),
  );
}

function assertBoundedInteger(value: number, name: string, min: number, max: number): void {
  if (!Number.isInteger(value) || value < min || value > max) {
    throw new Error('SHADOW_FILM_INPUT_INVALID');
  }
}

// Argument builders are pure and exported so tests pin the exact command
// surface without executing ffmpeg. Every interpolated value is a validated
// integer or a caller-owned path — no user-controlled strings reach the
// argument vector.
export function buildSynthesizeClipArgs(outputPath: string, durationSeconds: number): string[] {
  assertBoundedInteger(durationSeconds, 'durationSeconds', 1, 60);
  return [
    '-hide_banner',
    '-loglevel', 'error',
    // testsrc2 is a deterministic moving test pattern generated by lavfi:
    // nothing is read from disk or network, and every run produces the same
    // frames, which is what makes the diagnostic's numbers comparable.
    '-f', 'lavfi',
    '-i', `testsrc2=size=640x360:rate=30:duration=${durationSeconds}`,
    '-pix_fmt', 'yuv420p',
    '-y', outputPath,
  ];
}

export function buildExtractFramesArgs(
  inputPath: string,
  outputPattern: string,
  intervalSeconds: number,
  maxFrames: number,
): string[] {
  assertBoundedInteger(intervalSeconds, 'intervalSeconds', 1, 30);
  assertBoundedInteger(maxFrames, 'maxFrames', 1, FILM_STUDY_MAX_FRAMES_PER_JOB);
  return [
    '-hide_banner',
    '-loglevel', 'error',
    '-i', inputPath,
    '-vf', `fps=1/${intervalSeconds}`,
    '-frames:v', String(maxFrames),
    '-q:v', '4',
    '-y', outputPattern,
  ];
}

async function runFfmpeg(args: string[]): Promise<number> {
  const start = Date.now();
  try {
    await execFileAsync('ffmpeg', args, { timeout: FFMPEG_TIMEOUT_MS });
  } catch (error) {
    if ((error as NodeJS.ErrnoException)?.code === 'ENOENT') {
      throw new Error('SHADOW_FILM_FFMPEG_MISSING');
    }
    throw new Error('SHADOW_FILM_FFMPEG_FAILED');
  }
  return Date.now() - start;
}

export interface SynthesizedClip {
  clipPath: string;
  synthesizeMs: number;
}

/**
 * Generate a deterministic test clip inside `directory`. Used by the
 * measurement diagnostic so extraction timing needs no uploaded fixture.
 */
export async function synthesizeTestClip(options: {
  directory: string;
  durationSeconds: number;
}): Promise<SynthesizedClip> {
  const clipPath = path.join(options.directory, 'diagnostic-clip.mp4');
  const synthesizeMs = await runFfmpeg(buildSynthesizeClipArgs(clipPath, options.durationSeconds));
  return { clipPath, synthesizeMs };
}

export interface ExtractedFrames {
  framePaths: string[];
  extractMs: number;
}

/**
 * Extract JPEG frames from a clip at the stated sampling policy. Frames are
 * written into `directory` and NEVER anywhere else: the Film Study retention
 * rule (#103 prerequisite 3) is that extracted frames live only in a
 * per-request temp directory and are deleted after inference — callers own
 * that cleanup, and nothing here writes to blob storage.
 */
export async function extractFrames(options: {
  clipPath: string;
  directory: string;
  intervalSeconds?: number;
  maxFrames?: number;
}): Promise<ExtractedFrames> {
  const intervalSeconds = options.intervalSeconds ?? FILM_STUDY_FRAME_INTERVAL_SECONDS;
  const maxFrames = options.maxFrames ?? FILM_STUDY_MAX_FRAMES_PER_JOB;
  const outputPattern = path.join(options.directory, 'frame-%03d.jpg');
  const extractMs = await runFfmpeg(
    buildExtractFramesArgs(options.clipPath, outputPattern, intervalSeconds, maxFrames),
  );
  const entries = await fs.readdir(options.directory);
  const framePaths = entries
    .filter((name) => /^frame-\d{3}\.jpg$/.test(name))
    .sort()
    .map((name) => path.join(options.directory, name));
  // ffmpeg exiting 0 while producing nothing is still a failure: an executor
  // (or the diagnostic) proceeding with zero frames would "succeed" while
  // measuring or analyzing nothing.
  if (framePaths.length === 0) {
    throw new Error('SHADOW_FILM_FFMPEG_FAILED');
  }
  return { framePaths, extractMs };
}

export interface VisionFrameAnalysis {
  content: string;
  latencyMs: number;
  promptTokens: number | null;
  completionTokens: number | null;
  reasoningTokens: number | null;
}

/**
 * One chat-completions call to the vision deployment with a batch of JPEG
 * frames. Throws SHADOW_-coded errors in the processor's vocabulary so the
 * eventual film_study executor reuses this unchanged.
 */
export async function analyzeFramesWithVision(options: {
  frames: Buffer[];
  prompt: string;
  maxCompletionTokens?: number;
  timeoutMs?: number;
  env?: Record<string, string | undefined>;
}): Promise<VisionFrameAnalysis> {
  const env = options.env ?? process.env;
  if (!isFilmStudyVisionConfigured(env)) {
    throw new Error('SHADOW_FILM_VISION_UNCONFIGURED');
  }
  if (
    options.frames.length === 0
    || options.frames.length > FILM_STUDY_MAX_FRAMES_PER_JOB
    || options.frames.some((frame) => frame.length === 0 || frame.length > MAX_FRAME_BYTES)
  ) {
    throw new Error('SHADOW_FILM_INPUT_INVALID');
  }

  const endpoint = env.AZURE_AI_ENDPOINT!.trim().replace(/\/+$/, '');
  const deployment = getVisionDeploymentName(env);
  const apiVersion = env.AZURE_AI_VISION_API_VERSION?.trim()
    || env.AZURE_AI_API_VERSION?.trim()
    || '2024-12-01-preview';
  const url = `${endpoint}/openai/deployments/${encodeURIComponent(deployment)}/chat/completions?api-version=${encodeURIComponent(apiVersion)}`;

  const content: Array<Record<string, unknown>> = [
    { type: 'text', text: options.prompt },
    ...options.frames.map((frame) => ({
      type: 'image_url',
      image_url: { url: `data:image/jpeg;base64,${frame.toString('base64')}` },
    })),
  ];

  const start = Date.now();
  let response: Response;
  try {
    response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'api-key': env.AZURE_AI_KEY!.trim() },
      signal: AbortSignal.timeout(options.timeoutMs ?? VISION_TIMEOUT_MS),
      body: JSON.stringify({
        messages: [{ role: 'user', content }],
        // No temperature: gpt-5-family reasoning deployments reject any
        // non-default value outright (HTTP 400) — same measured fact that
        // broke every background job before shadowJobProcessor.ts learned it.
        // Reasoning tokens spend from max_completion_tokens, so the floor
        // stays at 4096 (guardrails §6).
        max_completion_tokens: options.maxCompletionTokens ?? VISION_MAX_COMPLETION_TOKENS,
      }),
    });
  } catch {
    throw new Error('SHADOW_AI_PROVIDER_UNAVAILABLE');
  }

  if (!response.ok) {
    // Never read, persist, return, or log the provider response body.
    console.error('SHADOW film-study vision request failed', { status: response.status });
    throw new Error('SHADOW_AI_PROVIDER_ERROR');
  }

  const latencyMs = Date.now() - start;
  const data = await response.json() as {
    choices?: Array<{ message?: { content?: unknown } }>;
    usage?: {
      prompt_tokens?: unknown;
      completion_tokens?: unknown;
      completion_tokens_details?: { reasoning_tokens?: unknown };
    };
  };
  const text = data.choices?.[0]?.message?.content;
  if (typeof text !== 'string' || !text.trim()) {
    throw new Error('SHADOW_AI_EMPTY_RESPONSE');
  }

  const asCount = (value: unknown): number | null => (
    typeof value === 'number' && Number.isFinite(value) ? value : null
  );

  return {
    content: text,
    latencyMs,
    promptTokens: asCount(data.usage?.prompt_tokens),
    completionTokens: asCount(data.usage?.completion_tokens),
    reasoningTokens: asCount(data.usage?.completion_tokens_details?.reasoning_tokens),
  };
}
