'use client';

import { useEffect, useRef, useState } from 'react';

import { apiBase } from '@/lib/apiBase';
import type { WallBoard, WallSession } from '@/src/server/pilot/wallDisplay';

/**
 * THE WALL — the board on the gym's television.
 *
 * This is not a page in the sense the other 68 are. Nobody signs into it,
 * nobody taps it, and nobody is standing closer than about fifteen feet. So it
 * breaks the house shell on purpose:
 *
 *   - No RoleStandaloneView. That shell brings a session bar, a breadcrumb
 *     trail, an Operations link and a Shadow chat button -- four controls on a
 *     screen with no pointer attached to it. GlobalRoleHeader stands down on
 *     this route for the same reason.
 *   - No hover states and no focus rings, because there is no cursor and no
 *     keyboard. Every element here is text.
 *   - The type starts where the desk surfaces stop. The φ ladder's top rung is
 *     --t-5xl at 80.9px, which is a hero size on a laptop; here it is the
 *     BODY size for a name, and the clock sits two rungs above it. globals.css
 *     already continues the ladder past the named rungs (--text-7xl through
 *     --text-9xl, generated by √φ), which is exactly what a wall needs and what
 *     nothing else in the app had a use for.
 *   - Nothing scrolls. The viewport is the page: h-screen, overflow hidden, and
 *     every list hard-capped server-side so a busy night cannot push the
 *     marquee off the bottom of a 16:9 panel.
 *
 * It is the ink ground (Law 6, staff side) in .room--floor: brick and caged
 * lamps, which is the room this screen is physically bolted to.
 */

/** Steady state: the board is a live read, and thirty seconds is live enough. */
export const WALL_POLL_MS = 30_000;

/**
 * After a failure, ask again SOONER, not later. A wall coming back within five
 * seconds of the network returning is the difference between "the screen was
 * out for a moment" and "the screen is broken". The ramp exists only so a
 * genuinely dead backend is not hammered forever.
 */
export function nextPollDelayMs(consecutiveFailures: number): number {
  if (consecutiveFailures <= 0) return WALL_POLL_MS;
  return Math.min(5_000 * 2 ** (consecutiveFailures - 1), WALL_POLL_MS);
}

/** Five minutes without a good read: say so. Twenty: stop claiming. */
export const WALL_STALE_MS = 5 * 60_000;
export const WALL_ABANDON_MS = 20 * 60_000;

export type WallHealth = 'fresh' | 'stale' | 'abandoned' | 'never';

/**
 * How much the board is still allowed to assert.
 *
 * "Who is on the floor" is the one panel that rots: a list from forty minutes
 * ago is not a stale fact, it is a false one -- it names children as being in a
 * room they may have left. So past WALL_ABANDON_MS the board stops showing it
 * and stands down to the crest and the clock, which are true regardless.
 */
export function boardHealth(lastGoodAtMs: number | null, nowMs: number): WallHealth {
  if (lastGoodAtMs === null) return 'never';
  const age = nowMs - lastGoodAtMs;
  if (age >= WALL_ABANDON_MS) return 'abandoned';
  if (age >= WALL_STALE_MS) return 'stale';
  return 'fresh';
}

interface WallResponse {
  ok?: boolean;
  board?: WallBoard;
}

export default function WallDisplay() {
  const [board, setBoard] = useState<WallBoard | null>(null);
  const [lastGoodAt, setLastGoodAt] = useState<number | null>(null);
  const [connected, setConnected] = useState(true);
  const [now, setNow] = useState<number | null>(null);
  const mounted = useRef(true);

  /* The clock is read from the browser, not from the payload and not from the
     server. The television is in the room; its clock is the gym's clock, and it
     keeps telling the right time when the backend is down -- which is precisely
     when a blank screen would be most embarrassing.

     It starts null, and that is not an oversight. This route prerenders, so a
     clock initialised from Date.now() would be BUILD time: the shipped HTML
     said "Monday, August 3, 4:22 PM" and every browser showed that stale
     instant until hydration, on the one screen in the building whose entire
     job is to be true. Null renders a held space instead, and the first tick
     fills it. */
  useEffect(() => {
    // The wall clock IS an external system, and this is the subscribe step:
    // read it once on mount so the masthead fills immediately rather than
    // holding blank for the first second, then follow it. Same exemption
    // CoachWorkspace takes for its own on-mount reads.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setNow(Date.now());
    const tick = setInterval(() => setNow(Date.now()), 1_000);
    return () => clearInterval(tick);
  }, []);

  useEffect(() => {
    mounted.current = true;
    let timer: ReturnType<typeof setTimeout> | undefined;
    let failures = 0;
    // One read at a time. Without this, a visibilitychange arriving mid-request
    // starts a second poll, both finish and both schedule a timer, and only the
    // later one is tracked -- so the orphan keeps firing and the wall quietly
    // doubles its request rate every time the TV wakes up.
    let inFlight = false;

    async function poll(): Promise<void> {
      if (inFlight) return;
      inFlight = true;
      try {
        /* credentials: 'omit' is stated rather than left to the default, and
           rather than taking a line in the convention test's allowlist. The
           gear shop established that pattern (#193): an explicit omission at
           the call site is a claim the reader can check, where an allowlist
           entry is a claim in another file that drifts away from the fetch it
           describes. Nobody signs in to a television, so there is no session
           cookie here to send -- and /api/pilot/wall is built to be safe as a
           public document anyway: the organization is never taken from the
           caller, raw athlete ids never leave the server, and every name is
           gated per athlete in src/server/pilot/wallDisplay.ts. */
        const response = await fetch(`${apiBase()}/api/pilot/wall`, {
          cache: 'no-store',
          credentials: 'omit',
        });
        if (!response.ok) throw new Error('unavailable');
        const payload = (await response.json()) as WallResponse;
        if (!payload.ok || !payload.board) throw new Error('unavailable');
        if (!mounted.current) return;

        failures = 0;
        setBoard(payload.board);
        setLastGoodAt(Date.now());
        setConnected(true);
      } catch {
        if (!mounted.current) return;
        failures += 1;
        setConnected(false);
        // The last good board deliberately stays on screen, dated. A wall that
        // blanks on a dropped packet is worse than one that admits its age.
      } finally {
        // In `finally` so the early returns above cannot leave the display
        // holding a lock it never releases -- a wall that stops asking is a
        // wall that is wrong for the rest of the evening.
        inFlight = false;
        if (mounted.current) {
          timer = setTimeout(() => void poll(), nextPollDelayMs(failures));
        }
      }
    }

    function refreshNow() {
      // A TV browser throttles or suspends a backgrounded tab; coming back
      // should not mean waiting out a timer that never fired.
      if (typeof document !== 'undefined' && document.visibilityState !== 'visible') return;
      if (timer) clearTimeout(timer);
      void poll();
    }

    void poll();

    if (typeof document !== 'undefined') {
      document.addEventListener('visibilitychange', refreshNow);
    }

    return () => {
      mounted.current = false;
      if (timer) clearTimeout(timer);
      if (typeof document !== 'undefined') {
        document.removeEventListener('visibilitychange', refreshNow);
      }
    };
  }, []);

  // Before the clock has landed the board makes no claim about its own age.
  // Reading Date.now() here instead would be an impure call during render, and
  // the honest answer for that one frame is "nothing known yet" anyway.
  const health: WallHealth = now === null ? 'never' : boardHealth(lastGoodAt, now);
  const zone = board?.time_zone;
  const showLive = board !== null && health !== 'abandoned';

  return (
    <div className="wall-board flex h-screen w-screen flex-col overflow-hidden">
      <Masthead now={now} zone={zone} />

      {showLive ? (
        <LiveBoard board={board} zone={zone} />
      ) : (
        <StandingBoard health={health} />
      )}

      <FootRule board={showLive ? board : null} health={health} connected={connected} zone={zone} />
    </div>
  );
}

/* ------------------------------------------------------------- masthead --- */

/** A held space, so the masthead's geometry does not jump when the clock lands. */
const HELD = ' ';

function Masthead({ now, zone }: { now: number | null; zone?: string }) {
  const stamp = now === null ? null : new Date(now);
  return (
    <header className="flex shrink-0 items-end justify-between gap-[var(--s6)] px-[var(--s7)] pt-[var(--s5)]">
      <div>
        <p className="wall-eyebrow">Punxsy Prominence Boxing &amp; Fitness</p>
        <p className="wall-day text-6xl">{stamp ? formatIn(stamp, zone, { weekday: 'long' }) : HELD}</p>
        <p className="wall-date text-4xl">
          {stamp ? formatIn(stamp, zone, { month: 'long', day: 'numeric', year: 'numeric' }) : HELD}
        </p>
      </div>
      {/* aria-hidden: a clock that announces itself every minute is hostile to
          anyone running a reader near this screen, and the time is not the
          reason a person would be listening to a wall. */}
      <p className="wall-clock text-8xl" aria-hidden="true">
        {stamp ? formatIn(stamp, zone, { hour: 'numeric', minute: '2-digit' }) : HELD}
      </p>
    </header>
  );
}

/* ----------------------------------------------------------- live board --- */

function LiveBoard({ board, zone }: { board: WallBoard; zone?: string }) {
  return (
    <>
      {/* The golden section, not a half. --split-major / --split-minor are the
          system's own 61.8 / 38.2 tokens (Law 8). */}
      <main className="grid min-h-0 flex-1 grid-cols-[var(--split-major)_var(--split-minor)] gap-[var(--s6)] px-[var(--s7)] py-[var(--s5)]">
        <OnTheFloor board={board} />
        <Today sessions={board.sessions} zone={zone} />
      </main>
      <Marquee board={board} />
    </>
  );
}

/**
 * How hard the floor list has to work to fit. The thresholds assume the worst
 * case for width -- everyone consented to a full name -- because that is the
 * case that overflows, and a list that clips its last row is a list that lies
 * about who is in the room.
 */
export function floorDensity(shown: number): 'roomy' | 'dense' | 'packed' {
  if (shown <= 8) return 'roomy';
  if (shown <= 14) return 'dense';
  return 'packed';
}

function OnTheFloor({ board }: { board: WallBoard }) {
  const overflow = board.on_floor_total - board.on_floor.length;

  return (
    <section className="flex min-h-0 flex-col" aria-label="On the floor">
      <h2 className="wall-heading">
        On the floor
        {board.on_floor_total > 0 && <span className="wall-count">{board.on_floor_total}</span>}
      </h2>

      {board.on_floor_total === 0 ? (
        // Honest, and not an error: an empty gym at 6am is a true fact about
        // the room, so it is stated as one rather than dressed as a fault.
        <p className="wall-quiet text-4xl">Nobody checked in yet today.</p>
      ) : board.on_floor.length === 0 ? (
        // name_mode is 'off': the count is real, the names are withheld.
        <p className="wall-quiet text-4xl">
          {board.on_floor_total} {board.on_floor_total === 1 ? 'person' : 'people'} training.
        </p>
      ) : (
        // Density steps the names down the φ ladder as the room fills, so a
        // busy class does not overflow the panel and get silently clipped. See
        // the [data-density] rules in globals.css.
        <ul className="wall-floor-list min-h-0" data-density={floorDensity(board.on_floor.length)}>
          {board.on_floor.map((person) => (
            <li key={person.key} className="wall-name text-6xl">
              {person.name}
            </li>
          ))}
          {overflow > 0 && <li className="wall-more text-4xl">+{overflow} more</li>}
        </ul>
      )}
    </section>
  );
}

/* Session state -- upcoming / on now / done -- is decided server-side at read
   time rather than recomputed here against the browser clock. The board is
   thirty seconds fresh, so the worst case is a class showing as upcoming for
   half a minute after it starts, and the alternative is a second clock on the
   screen that can disagree with the first one. */
function Today({ sessions, zone }: { sessions: readonly WallSession[]; zone?: string }) {
  return (
    <section className="flex min-h-0 flex-col" aria-label="Today">
      <h2 className="wall-heading">Today</h2>

      {sessions.length === 0 ? (
        <p className="wall-quiet text-4xl">Nothing on the schedule.</p>
      ) : (
        <ul className="wall-session-list min-h-0">
          {sessions.map((session) => (
            <li key={session.key} className={`wall-session wall-session--${session.state}`}>
              <span className="wall-session-time text-4xl">{formatClock(session.start_at, zone)}</span>
              <span className="wall-session-title text-3xl">{session.title}</span>
              <span className="wall-session-meta">
                {session.state === 'cancelled'
                  ? 'Cancelled'
                  : session.state === 'now'
                    ? 'On now'
                    : session.location || ''}
              </span>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

/**
 * THE MARQUEE.
 *
 * .marquee did not exist in the design system. The Phase 2 roadmap says it did
 * -- "`.marquee` already exists in the design system with zero consumers" --
 * and that is simply not true of design-system/ppbf.css as it stands; it was
 * anticipated in prose and never written. The rules live in globals.css under
 * [data-surface="wall"], and wallSurface.test.tsx pins both halves together.
 *
 * It travels. On the brightest band of a screen that runs twelve hours a day,
 * continuously moving pixels is the single best burn-in defence available, and
 * a travelling sign is what a marquee IS. Under prefers-reduced-motion it
 * stops dead and becomes a list.
 */
function Marquee({ board }: { board: WallBoard }) {
  const items = board.marquee;

  if (items.length === 0) {
    // No crossing in the window. The band stays -- a layout that reflows when
    // news arrives draws the eye to the wrong thing -- and states the ladder
    // itself, which is a true thing about the gym rather than an invented
    // number.
    return (
      <section className="marquee marquee--idle" aria-label="Milestones">
        <p className="marquee-idle-line">
          <span className="marquee-idle-label">The ladder</span>
          <span aria-hidden="true">5 · 13 · 34 · 89 · 233</span>
          <span className="sr-only">5, 13, 34, 89, 233 sessions</span>
        </p>
      </section>
    );
  }

  // Duration scales with content so the travel SPEED is constant however many
  // names are up: eight seconds of screen time per name.
  const seconds = Math.max(24, items.length * 8);

  return (
    <section className="marquee" aria-label="Milestones">
      <div className="marquee-track" style={{ ['--marquee-secs' as string]: `${seconds}s` }}>
        {/* Two passes of the same list make the loop seamless. The second is
            hidden from the accessibility tree so a reader is not told the same
            child crossed the same milestone twice. */}
        <ul className="marquee-run">
          {items.map((item) => (
            <li key={item.key} className="marquee-item">
              <span className="marquee-mark" aria-hidden="true">
                ★
              </span>
              <span className="marquee-name">{item.name}</span>
              <span className="marquee-count">{item.milestone}</span>
              <span className="marquee-unit">sessions</span>
            </li>
          ))}
        </ul>
        <ul className="marquee-run" aria-hidden="true">
          {items.map((item) => (
            <li key={`echo-${item.key}`} className="marquee-item">
              <span className="marquee-mark">★</span>
              <span className="marquee-name">{item.name}</span>
              <span className="marquee-count">{item.milestone}</span>
              <span className="marquee-unit">sessions</span>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}

/* ------------------------------------------------------- standing board --- */

/**
 * What the room sees when there is no board: the gym's name, and nothing
 * claimed. No status code, no stack trace, no "Failed to fetch" in 100px type
 * in front of forty people. The masthead above and the clock keep running,
 * because they are true without a network.
 */
function StandingBoard({ health }: { health: WallHealth }) {
  return (
    <main className="flex min-h-0 flex-1 flex-col items-center justify-center gap-[var(--s5)] px-[var(--s7)]">
      <p className="wall-standing-crest" aria-hidden="true">
        PPBF
      </p>
      <p className="wall-standing-line text-5xl">
        {health === 'never' ? 'The board is coming up.' : 'The board is reconnecting.'}
      </p>
    </main>
  );
}

/* ------------------------------------------------------------ foot rule --- */

/**
 * The gym's own voice, and the board's own honesty, on one line.
 *
 * The notice comes from pilot.announcements at the gym_notices placement --
 * the same copy the signed-out login page already shows the public, so nothing
 * reaches this screen that was not already written for people who are not
 * members. The posting UI exists today at /notices; this slot is live, not a
 * stub.
 */
function FootRule({
  board,
  health,
  connected,
  zone,
}: {
  board: WallBoard | null;
  health: WallHealth;
  connected: boolean;
  zone?: string;
}) {
  return (
    <footer className="flex shrink-0 items-center justify-between gap-[var(--s6)] px-[var(--s7)] pb-[var(--s5)] pt-[var(--s4)]">
      <div className="min-w-0">
        {board?.notice ? (
          <p className="wall-notice text-4xl">
            <span className="wall-notice-msg">{board.notice.message}</span>
            {board.notice.author && <span className="wall-notice-by">— {board.notice.author}</span>}
          </p>
        ) : (
          // The slot is kept whether or not anyone has posted. An empty line
          // here is the gym choosing not to say anything today, which is a
          // different thing from the slot not existing.
          <p className="wall-notice wall-notice--empty text-4xl">Nothing posted today.</p>
        )}
      </div>

      <p className="wall-stamp">
        {health === 'fresh' && connected
          ? 'Live'
          : board
            ? `As of ${formatClock(board.generated_at, zone)}`
            : 'Standing by'}
      </p>
    </footer>
  );
}

/* ------------------------------------------------------------- helpers --- */

/**
 * Postgres hands a timestamptz back as "2026-08-03 17:00:00+00", which is not
 * ISO-8601 and which some engines refuse. A wall must never print "Invalid
 * Date" at 60px, so this normalises what it can and returns null for the rest;
 * every caller renders an em dash instead.
 */
export function parseTimestamp(raw: string | null | undefined): Date | null {
  if (!raw) return null;
  const normalized = raw.trim().replace(' ', 'T');
  const parsed = Date.parse(normalized);
  if (!Number.isNaN(parsed)) return new Date(parsed);
  const retry = Date.parse(raw);
  return Number.isNaN(retry) ? null : new Date(retry);
}

function formatIn(value: Date, zone: string | undefined, options: Intl.DateTimeFormatOptions): string {
  try {
    return new Intl.DateTimeFormat(undefined, { ...options, ...(zone ? { timeZone: zone } : {}) }).format(value);
  } catch {
    // An unknown IANA zone from the payload must not take the clock out.
    return new Intl.DateTimeFormat(undefined, options).format(value);
  }
}

export function formatClock(raw: string | null | undefined, zone?: string): string {
  const parsed = parseTimestamp(raw);
  if (!parsed) return '—';
  return formatIn(parsed, zone, { hour: 'numeric', minute: '2-digit' });
}
